### ISSUE TITLE
Just to thanks you =)

### ISSUE THREAD

**Issue by aleluff** [beenotung/quick-erd#2]
Hi,

Thanks for your works, It help me so much to implement ERD
Here is the project : web-db.app
Feedbacks are welcomed =)

Best

**Comment by aleluff** [comment]
Thanks =)

It's a pure coincidence for relation line overlap  =)
To be truly honest, I didn't change so much things, expect rendering and and do not render before placment

Your code was enough for the feature, I will finish all relation type in days and it will be the real soft for ERD

**Comment by aleluff** [comment]
I you want a perpetual ultimate, it would be a great reward, tell me

**Comment by beenotung** [comment]
I prefer to store the erd text with git over storing in the cloud service.
You can show appreciation by linking to this project in credit/acknowledgement/about page :)

**Comment by aleluff** [comment]
It's not a cloud service, it's an offline web app
I looked for you on twitter but you weren't there 
If someday I do a credit page, I will think think about you =)

**Comment by beenotung** [comment]
FYI, my twitter handle is the same as github
